FROM alpine:3.5

# ncurses is required for Gradle's prettier console output mode
RUN apk add --update --no-cache \
      openjdk8=8.121.13-r0 \
      ncurses5-libs=5.9-r1 \
      ncurses-terminfo=6.0-r7
